[build]
builder = "nixpacks"
buildCommand = "cd src/MortalKombatCompiler.Backend/MortalKombatCompiler.API && dotnet restore && dotnet publish -c Release -o ./publish"

[deploy]
startCommand = "cd src/MortalKombatCompiler.Backend/MortalKombatCompiler.API/publish && ./MortalKombatCompiler.API --urls http://0.0.0.0:${PORT}"

[env]
ASPNETCORE_ENVIRONMENT = "Production"
