[build]
builder = "dockerfile"
dockerfilePath = "src/MortalKombatCompiler.Backend/MortalKombatCompiler.API/Dockerfile"

[deploy]
startCommand = "./MortalKombatCompiler.API --urls http://0.0.0.0:${PORT}"

[env]
ASPNETCORE_ENVIRONMENT = "Production"